config/routes.rb
Rails.application.routes.draw do
  get 'bookings/create'
  get 'bookings/show'
  # get 'listings/index'
  # get 'listings/show'
  # get 'listings/new'
  # get 'listings/edit'
  devise_for :users
  root to: 'listings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :listings do
    resources :bookings, only: [:show, :create]
  end
  get '/users/dashboard', to: 'pages#dashboard'
  get '/users/profile', to: 'users#show'
  get '/users/profile/edit', to: 'users#edit'
  patch '/users/profile', to: 'users#update'
  get '/tagged', to: "listings#tagged", as: :tagged
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  has_many :reviews

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :total_price, presence: true
end

app/models/listing.rb
class Listing < ApplicationRecord
  mount_uploader :image, PhotoUploader

  acts_as_taggable_on :tags
  validates :tag_list, presence: true

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings

  validates :price, presence: true
  validates :image, presence: true
  validates :detail, presence: true
  validates :brand, presence: true
  validates :size, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # include PgSearch
  # pg_search_scope :search_by_brand_and_detail,
  #   against: [ :brand, :detail ],
  #   using: { tsearch: { prefix: true } }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :listings
  has_many :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: [:index, :show], unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: [:index, :show], unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def after_sign_in_path_for(resource)
    listings_path
  end

  def after_sign_out_path_for(resource)
    listings_path
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    set_listing
    @booking = Booking.new(booking_params)
    @booking.listing = @listing
    @booking.user = current_user
    @booking.total_price = @listing.price

    authorize @booking

    if @booking.save
      redirect_to listing_booking_path(@listing, @booking)
    else
      render "listings/show"
    end

  end

  def show
    set_listing
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_listing
    @listing = Listing.find(params[:listing_id])
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  def index
    @listings = Listing.all
    @tags = ActsAsTaggableOn::Tag.most_used(5)
    # search bar

    if params[:query].present?
      sql_query = " \ brand @@ :query \ OR detail @@ :query \ "
      @listings = Listing.where(sql_query, query: "%#{params[:query]}%")
    else
      @listings = Listing.all
    end
  end

  def show
    set_listing
    @booking = Booking.new
    @user = current_user

    # mapbox

    @marker = {
      lat: @listing.latitude,
      lng: @listing.longitude,
      image_url: helpers.asset_url('heel_marker.png')
    }
  end

  def new
    @listing = Listing.new
    authorize @listing
  end

  def create
    @listing = Listing.new(listing_params)
    authorize @listing
    @listing.user = current_user
    if @listing.save
      redirect_to listing_path(@listing)
    else
      render :new
    end
  end

  def edit
    set_listing
    authorize @listing
  end

  def update
    set_listing
    authorize @listing
    if @listing.update(listing_params)
      redirect_to listings_path
    else
      redirect_to listings_path
    end
  end

  def destroy
    authorize @listing
    @listing.destroy
    @user = current_user
    redirect_to users_dashboard_path(@user)
  end

  def tagged
    @listings = Listing.tagged_with(params[:tag]) if params[:tag].present?
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:price, :detail, :brand, :size, :address, :image, tag_list: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    @user = current_user
    @bookings = @user.bookings
    @listings = @user.listings
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end

  def edit
    @user = current_user
    authorize @user
  end

  def update
    @user = current_user
    authorize @user
    @user.update(user_params)
    redirect_to users_profile_path
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<h1>Booking Confirmation</h1>
<hr>
<div class="big-box">
  <div class="img">
    <%= cl_image_tag @listing.image, height: 646, width: 464, class: "img"  %>
  </div>
  <div class="container confirm">
    <table>
      <tr>
        <th class="left">Booking Start Date: </th>
        <th><%= @booking.start_date.strftime("%F") %></th>
      </tr>
      <tr>
        <th class="left">Booking End Date: </th>
        <th><%= @booking.end_date.strftime("%F") %></th>
      </tr>
      <tr>
        <th class="left">Brand: </th>
        <th><%= @listing.brand %></th>
      </tr>
      <tr>
        <th class="left">Description: </th>
        <th><%= @listing.detail %></th>
      </tr>
      <tr>
        <th class="left">Price: </th>
        <th><%= @listing.price %></th>
      </tr>
      <tr>
        <th class="left">Size: </th>
        <th><%= @listing.size %></th>
      </tr>
    </table>
    <div><%= link_to "Go back to index", listings_path, class: "button" %></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/listings/edit.html.erb
<h1> Edit an Item</h1>
<div class="banner">
</div>
<div class="container">
  <div class="form">
    <%= simple_form_for @listing do |f| %>
      <%= f.file_field :image %>
      <%= f.input :price, placeholder: '$1000/day' %>
      <%= f.input :size, placeholder: 'S-6-10-38'%>
      <%= f.input :brand, placeholder: 'Chanel'%>
      <%= f.input :detail, placeholder: 'Chanel Cotton Tweed Coral & White Dress Spring-Summer 2019' %>
      <%= f.input :address, placeholder: '819 West Nanjing Road Shanghai' %>
      <%= f.button :submit, class: "button" %>
    <% end %>
  </div>
</div>

app/views/listings/index.html.erb
<!-- banner -->
<div class="banner"> Rent & Shine
  <p class="tagline"> Dress with Benefits | No Strings Attached</p>
</div>
<div class="container">
  <% @tags.each do |tag| %>
    <div class="d-flex">
      <div id="<%= tag.name%>">
        <h2 class="category">
          <% if @listings.tagged_with(tag.name).size > 0 %>
            <%= tag.name %>
            <div class="number">(<%=@listings.tagged_with(tag.name).size %>)</div>
          <% end %>
        </h2>
      </div>
    </div>
    <div class="row">
      <% @listings.tagged_with(tag.name).each do |listing| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="card" >
            <%= cl_image_tag listing.image, class: "card-img" %>
            <div class="card-description">
              <p id="brand"><%=listing.brand%></p>
              <p><i><%=listing.detail%></i></p>
              <p><%=listing.size%></p>
              <p>$<%=listing.price%>/day</p>
            </div>
          </div>
          <%= link_to "", listing_path(listing), class: 'card-link' %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/listings/new.html.erb
<div class="banner">
</div>
<div class="container" id="form-top">
  <div class="form">
    <%= simple_form_for @listing do |f| %>
      <%= f.input :image %>
      <%= f.input :price, placeholder: '$1000/day' %>
      <%= f.input :size, placeholder: 'S-6-10-38'%>
      <%= f.input :brand, placeholder: 'Chanel'%>
      <%= f.input :detail, placeholder: 'Chanel Cotton Tweed Coral & White Dress Spring-Summer 2019' %>
      <%= f.input :tag_list, as: :check_boxes, collection: ["Black Tie", "Cocktail", "Party", "Smart casual", "Wedding"], label: "Dress Code" %>
      <%= f.input :address, placeholder: '819 West Nanjing Road Shanghai'%>
      <%= f.button :submit, class: "button" %>
    <% end %>
  </div>
</div>

app/views/listings/show.html.erb
<div class="show">
  <div class="show-container">
    <div class="list-img"><%= cl_image_tag @listing.image, height: 646, width: 464, class: "list-img" %></div>
    <div class="box-right">
      <div class="upper-right">
        <% if @listing.user == @user %>
          <%= link_to "Edit this Listing", edit_listing_path(anchor: 'img-upload'), class: "button show-edit-btn"  %>
        <% end %>
        <div class="description">
          <h1><%= @listing.brand %></h1>
          <h4><%= @listing.detail %></h4>
          <div class="d-flex">
            <p><% @listing.tag_list.each do |tag| %>
                <p><%= link_to tag, listings_path(anchor: tag),class: "tags" %></p>
              <% end %></p>
          </div>
          <div class="size-price">
            <h5>¥ <%= @listing.price %> / day</h5>
            <h5>Size: <%= @listing.size %></h5>
          </div>
          <hr>
          <h4>Booking</h4>
          <div class="box-form">
            <div class="form-wrapper" style="width: 400px;">
              <%= simple_form_for [@listing, @booking] do |f| %>
                <%= f.input :start_date, as: :string, required: false, input_html: { class: "datepicker" } %>
                <%= f.input :end_date, as: :string, required: false, input_html: { class: "datepicker" } %>
              </div>
              <% if @listing.user != @user %>
                <div class="b-left"><%= f.button :submit, "Book", class: "button" %></div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div id="map" style="width: 100%; height: 200px;" data-marker="<%= @marker.to_json %>" data-mapbox-api-key= "<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="dash">
  <h1>Welcome <%= @user.email%>!</h1>
  <h2>Your Bookings</h2>
  <!-- booking card -->

  <div class="container">
    <% @bookings.each do |booking| %>
      <div class= "card-dash">
        <table>
          <tr>
            <th class="row-title">Rental Period:</th>
            <th><%= booking.start_date.strftime("From %F") %> <%= booking.end_date.strftime("to %F") %></th>
          </tr>
          <tr>
            <th class="row-title">Brand</th>
            <th><%=booking.listing.brand%></th>
          </tr>
          <tr>
            <th class="row-title">Description:</th>
            <th><%=booking.listing.detail%></th>
          </tr>
          <tr>
            <th class="row-title">Size:</th>
            <th><%=booking.listing.size%></th>
          </tr>
          <tr>
            <th class="row-title">Paid:</th>
            <th>$<%=booking.total_price%></th>
          </tr>
        </table>
        <%= cl_image_tag booking.listing.image, class: "card-img", id:"dash-img" %>
      </div>
    <% end %>

  </div>
  <!-- listing card -->
  <div class="middle-bar">
    <h2>Your Listings</h2>
    <%= link_to "Add listing", new_listing_path, class: "button"%>
  </div>
  <div class="container">
    <div class="row">
      <% @listings.each do |listing| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <%= link_to edit_listing_path(listing) do %>


            <i class="fas fa-edit"></i>
          <% end %>

          <!-- <i class="fas fa-trash"></i>  -->
          <i id="<%= listing.id %>" class="fas fa-trash hover-icon sweet-alert-link"></i>
          <%= link_to "", listing_path(listing), method: :delete, class: "hidden delete-link-#{listing.id}" %>

          <%#= link_to "Delete", listing_path(listing), method: :delete, id: "delete-link", class: "delete-link hidden" %>

          <%#= link_to listing_path(listing), method: :delete, id: "sweet-alert" do %>
            <!-- <i class="fas fa-trash"></i> -->
          <%# end %>
            <div class="card" >
              <%= cl_image_tag listing.image, class: "card-img" %>
              <div class="card-description">
                <p id="brand"><%=listing.brand%></p>
                <p><i><%=listing.detail%></i></p>
                <p><%=listing.size%></p>
                <p>$<%=listing.price%>/day</p>
              </div>
            </div>
            <%= link_to "", listing_path(listing), class: 'card-link' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
<hr>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<!-- navbar -->
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon ">
  <%= link_to listings_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>
  <%= form_tag listings_path, method: :get do %>
    <%= text_field_tag :query, params[:query], class: "form-control",placeholder: "Search for a dress" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li id="welcome">Welcome <%= current_user.email.match(/\w*/) %>!</li>
        <li class="nav-item">
          <%= link_to "Add dress", new_listing_path(anchor: "form-top"), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My dresses", users_dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <% user = current_user.email.match(/([a-zA-Z])/)%>
          <p class="avatar"><%= user[1].upcase %></p>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Add new listing", users_dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<h1>HI</h1>
<h1>HI</h1>
<h1>HI</h1>
<h1>HI</h1>

app/views/users/show.html.erb
<div class="show-container">
  <h1>General Account Settings</h1>
  <div class="container">
    <p><strong>First Name:</strong> <%= @user.first_name %></p>
    <p><strong>Last Name:</strong> <%= @user.last_name %></p>
    <p><strong>Email:</strong> <%= @user.email %></p>
    <p><strong>Address:</strong> <%= @user.address %></p>
    <%= link_to "Edit", users_profile_edit_path%>
  </div>
</div>